var:
  url-repo: https://github.com/ludo2ne/ENSAI-1A-SQL   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

author: Ludovic Deneuville

website:
  title: "Base de données"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#D1CE15"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Cours
        menu:
          - href: doc/cours/01-intro.qmd
            text: "Introduction"
          - href: doc/cours/02-bases-de-donnees.qmd
            text: "Base de données"
          - href: doc/cours/03-sql-intro.qmd
            text: "Introduction à SQL"
          - href: doc/cours/04-agregations.qmd
            text: "Agrégations"
          - href: doc/cours/05-algebre.qmd
            text: "Algèbre Relationnelle"
          - href: doc/cours/06-jointures.qmd
            text: "Jointures"
          - href: doc/cours/07-sql-avance.qmd
            text: "SQL avancé"
          - href: doc/cours/08-formalisation.qmd
            text: "Formalisation des BDD"
      - text: TP
        menu:
          - href: doc/tp/tp1.qmd
            text: "TP1 - Premières requêtes"
          - href: doc/tp/tp2.qmd
            text: "TP2 - Vintage"
          - href: doc/tp/tp3.qmd
            text: "TP3 - Discographie"
          - href: doc/tp/tp4.qmd
            text: "TP4 - Chess Unofficial Fed"
          - href: doc/tp/tp5.qmd
            text: "TP5 - NBA stats"
      - text: Outils
        menu:
          - href: doc/outils/datalab.qmd
            text: Datalab
          - href: doc/outils/tp-datalab.qmd
            text: TP Datalab
          - href: doc/outils/docker.qmd
            text: Docker
          - href: doc/outils/vm.qmd
            text: VM
    right:
      - text: Divers
        menu:
          - href: doc/glossaire.qmd
            text: Glossaire
          - href: doc/ressources.qmd
            text: Ressources
          - href: doc/decouverte.qmd
            text: Découverte
      - text: Examens
        menu:
          - href: doc/examens/bdr-2024.qmd
            text: Examen 2024
          - href: doc/examens/bdr-2025.qmd
            text: Examen 2025
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    toc: true
    toc-location: left
    toc-depth: 3
    toc-expand: 3
    number-sections: true
    number-depth: 3
  revealjs:
    css: styles-reveal.css
    theme: moon
    slide-number: c/t
    slide-level: 3
    controls: true

mermaid:
  theme: forest
code-line-numbers: false
from: markdown+emoji
lightbox: true