---
title: "Base de données relationnelles"
description: "Cours ENSAI de 1ère année"
author: "Ludovic Deneuville"
format: html
from: markdown+emoji
---

- 6h de cours
- 18h de TP/TD

## Contenu du cours

- Les bases de données
  - Les bases de données relationnelles
- Introduction au langage SQL
  - Opérations CRUD
  - Filtre sur les lignes
  - Dates, Gestion des valeurs nulles
- Les Agrégations
- L'Algébre relationnelle
- Les jointures
- SQL avancé (Vues, Index, Droits, CTE)
- Modélisation UML
  - Formes normales

## TP

- TP1 : Première requêtes SQL
  - DuckDB, fichier parquet des prénoms
  - SELECT, WHERE, ORDER BY, GROUP BY
- TP2 : Exercices vintages
  - Location de DVD, Ecole de musique, Rugby
  - INNER JOIN, CREATE TABLE, DATE
- TP3 : Discographie
  - HAVING, INSERT, SEQUENCE, LEFT JOIN
- TP4 : Unofficial Chess Federation
  - UPDATE, LEFT JOIN, EXISTS
- TP5 : NBA stats
  - Travail sur une base mal structurée
- TD6 : Modélisation
  - Dépendances fonctionnelles, Formes Normales, UML
